version: '3.8'

services:
  app:
    container_name: spring_app
    image: jiyoon0221/my-spring-app:latest  # 올바른 Docker 이미지명
    restart: always
    ports:
      - "443:443"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - my_network

networks:
  my_network:
    driver: bridge