# ?? URL ??
base-url: "https://${DOMAIN}"  # ?? ? ?? ????? ?? ??
redirect-url: "${REDIRECT_URL}"  # ?? ??? ?? ? ????? ?? ?? -> ??? ??? ?? ??

# ?? ??
withdrawn:
  delete-time: 60     # ? ??
  check-time: 30      # ? ?? ( delete-time ?? ?? ???? ??? ?? )

# ?? ??
server:
  ssl:
    key-store: "${KEY_STORE}"  # Base64 ??? ? ??? ?? ??
    key-store-type: "${KEY_STORE_TYPE}"
    key-store-password: "${KEY_STORE_PASS}"
  port: 443  # HTTPS ?? ??

# spring ???
spring:
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # ?? ??? ?? ( ??? ????? ??? ?? )
  time-zone: Asia/Seoul

  # DB ??
  datasource:
    url: jdbc:mysql://yoondb.cnwom4kocpo9.ap-northeast-2.rds.amazonaws.com:3306/yoondb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa ??
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    security:
      enable-csrf: false

  # jwt ??
  jwt:
    secret: "${JWT_SECRET}"
    expiration:
      access-token: 3600  # 1 day
      refresh-token: 604800  # 7 days

  # ?? ??? ??
  security:
    oauth2:
      client:
        google-path-uri: "/authorization/oauth2/code/google"
        kakao-path-uri: "/authorization/oauth2/code/kakao"
        naver-path-uri: "/authorization/oauth2/code/naver"

        registration:
          google:
            client-id: "${GOOGLE_CLIENT_ID}"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            scope:
              - profile
              - email
            redirect-uri: https://${DOMAIN}/login/oauth2/code/kakao

          kakao:
            client-id: "${KAKAO_CLIENT_ID}"
            client-secret: "${KAKAO_CLIENT_SECRET}"
            authorization-grant-type: authorization_code
            redirect-uri: https://${DOMAIN}/login/oauth2/code/kakao
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: "${NAVER_CLIENT_ID}"
            client-secret: "${NAVER_CLIENT_SECRET}"
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://${DOMAIN}/login/oauth2/code/kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo